# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Y3QY95K7wb-VT9sA_q79-pnFVwBKjdG
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import joblib
import xgboost as xgb

# --- KONFIGURASI HALAMAN ---
st.set_page_config(page_title="Prediksi Status Mahasiswa", layout="centered")

# --- LOAD MODEL ---
# Pastikan file 'xgboost.pkl' berada di direktori yang sama dengan script ini
@st.cache_resource
def load_model():
    try:
        model = joblib.load('xgboost.pkl')
        return model
    except Exception as e:
        st.error(f"Gagal memuat model: {e}")
        return None

model = load_model()

# --- UI STYLE (Custom CSS agar mirip gambar) ---
st.markdown("""
    <style>
    .main {
        background-color: #1a1c24;
        color: white;
    }
    .stNumberInput, .stSelectbox, .stSlider {
        margin-bottom: 20px;
    }
    </style>
    """, unsafe_allow_html=True)

st.title("📄 Data Mahasiswa")

# --- SECTION 1: STATUS FINANSIAL ---
st.subheader("💰 Status Finansial")

col_fin1 = st.selectbox("Pembayaran SPP", ["Menunggak", "Lunas"], help="Status pembayaran SPP saat ini")
col_fin2 = st.selectbox("Status Beasiswa", ["Bukan Penerima", "Penerima"], help="Apakah mahasiswa menerima beasiswa")
col_fin3 = st.selectbox("Status Debitur / Utang", ["Tidak Berutang", "Berutang"], help="Status utang piutang mahasiswa")

st.markdown("---")

# --- SECTION 2: AKADEMIK ---
# Semester 1
st.subheader("📚 Semester 1")
sks_1 = st.slider("SKS Lulus (S1)", 0, 24, 5, key="sks1")
nilai_1 = st.number_input("Nilai Rata-rata (0-20) (S1)", 0.0, 20.0, 12.00, step=0.1)

st.markdown("---")

# Semester 2
st.subheader("📚 Semester 2")
sks_2 = st.slider("SKS Lulus (S2)", 0, 24, 4, key="sks2")
nilai_2 = st.number_input("Nilai Rata-rata (0-20) (S2)", 0.0, 20.0, 12.00, step=0.1)

st.markdown("---")

# --- SECTION 3: PROFIL ---
st.subheader("👤 Profil Mahasiswa")
usia = st.slider("Usia saat Enrollment", 15, 60, 19)
nilai_masuk = st.number_input("Nilai Masuk (0-200)", 0.0, 200.0, 130.0)

# --- LOGIKA PREDIKSI ---
if st.button("🔍 Prediksi Sekarang", use_container_width=True):
    if model is not None:
        # 1. Mapping Input (Sesuaikan dengan format saat training model)
        # Contoh sederhana mapping kategorikal ke numerik:
        data = {
            'pembayaran_spp': 1 if col_fin1 == "Menunggak" else 0,
            'beasiswa': 1 if col_fin2 == "Penerima" else 0,
            'debitur': 1 if col_fin3 == "Berutang" else 0,
            'sks_S1': sks_1,
            'nilai_S1': nilai_1,
            'sks_S2': sks_2,
            'nilai_S2': nilai_2,
            'usia_enrollment': usia,
            'nilai_masuk': nilai_masuk
        }

        # Buat DataFrame
        df_input = pd.DataFrame([data])

        # 2. Prediksi
        prediction = model.predict(df_input)

        # 3. Tampilkan Hasil
        st.success(f"Hasil Prediksi: {prediction[0]}")
    else:
        st.error("Model tidak tersedia. Pastikan 'xgboost.pkl' sudah benar.")