# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uunVplbSEcy5sv3BJ9XQ_zhiRGYw2VAh
"""



import sys
!{sys.executable} -m pip install streamlit
import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Load model dan preprocessor
@st.cache_resource
def load_models():
    model = joblib.load('xgboost_model.pkl')
    return model

model = load_models()

# Mapping label untuk tampilan (sesuaikan dengan target variabel setelah pemrosesan di notebook)
# Asumsi: 0 = Dropout, 1 = Enrolled/Graduate (setelah replace(2, median_status))
label_map = {0: 'Dropout', 1: 'Enrolled/Graduate'}

st.title("Prediksi Status Siswa (Dropout/Enrolled/Graduate)")
st.markdown("Masukkan data siswa untuk prediksi status kelulusan menggunakan XGBoost.")

# Define the exact features used by the preprocessor during model training
numerical_cols = [
    'Previous_qualification_grade', 'Admission_grade', 'Age_at_enrollment',
    'Curricular_units_1st_sem_credited', 'Curricular_units_1st_sem_evaluations',
    'Curricular_units_1st_sem_grade', 'Curricular_units_1st_sem_without_evaluations',
    'Curricular_units_2nd_sem_without_evaluations', 'Unemployment_rate',
    'Inflation_rate', 'GDP'
]
categorical_cols = [
    'Application_mode', 'Application_order', 'Course', 'Mothers_qualification',
    'Fathers_qualification', 'Mothers_occupation', 'Fathers_occupation',
    'Displaced', 'Gender'
]

feature_columns = numerical_cols + categorical_cols

# Buat input form dengan columns untuk layout rapi
with st.form("prediction_form"):
    st.subheader("Input Data Siswa")

    # Sidebar for numerical features
    st.sidebar.header("Numerical Features")
    age_at_enrollment = st.sidebar.slider("Age at Enrollment", 17, 70, 20)
    admission_grade = st.sidebar.slider("Admission Grade", 0.0, 200.0, 120.0)
    prev_qual_grade = st.sidebar.slider("Previous Qualification Grade", 0.0, 200.0, 120.0)
    cu1_credited = st.sidebar.slider("Curricular Units 1st Sem Credited", 0, 30, 0)
    cu1_evaluations = st.sidebar.slider("Curricular Units 1st Sem Evaluations", 0, 30, 6)
    cu1_grade = st.sidebar.slider("Curricular Units 1st Sem Grade", 0.0, 20.0, 12.0)
    cu1_without_evals = st.sidebar.slider("Curricular Units 1st Sem Without Evaluations", 0, 10, 0)
    cu2_without_evals = st.sidebar.slider("Curricular Units 2nd Sem Without Evaluations", 0, 10, 0)
    unemployment_rate = st.sidebar.slider("Unemployment Rate", 0.0, 20.0, 10.0)
    inflation_rate = st.sidebar.slider("Inflation Rate", -5.0, 10.0, 1.0)
    gdp = st.sidebar.slider("GDP", -10.0, 10.0, 0.0)

    # Main area for categorical features
    col1, col2, col3 = st.columns(3)
    with col1:
        application_mode = st.selectbox("Application Mode", list(range(1, 19)), index=0)
        application_order = st.selectbox("Application Order", list(range(1, 7)), index=0)
        gender = st.selectbox("Gender", [0, 1], format_func=lambda x: "Female" if x==1 else "Male")
    with col2:
        course = st.selectbox("Course", list(range(1, 19)), index=0)
        mothers_qualification = st.selectbox("Mothers Qualification", list(range(1, 40)), index=0)
        fathers_qualification = st.selectbox("Fathers Qualification", list(range(1, 40)), index=0)
    with col3:
        mothers_occupation = st.selectbox("Mothers Occupation", list(range(1, 50)), index=0)
        fathers_occupation = st.selectbox("Fathers Occupation", list(range(1, 50)), index=0)
        displaced = st.selectbox("Displaced", [0, 1], format_func=lambda x: "Yes" if x==1 else "No")

    # Kumpulkan semua input ke dict
    input_data = {
        'Age_at_enrollment': age_at_enrollment,
        'Admission_grade': admission_grade,
        'Previous_qualification_grade': prev_qual_grade,
        'Curricular_units_1st_sem_credited': cu1_credited,
        'Curricular_units_1st_sem_evaluations': cu1_evaluations,
        'Curricular_units_1st_sem_grade': cu1_grade,
        'Curricular_units_1st_sem_without_evaluations': cu1_without_evals,
        'Curricular_units_2nd_sem_without_evaluations': cu2_without_evals,
        'Unemployment_rate': unemployment_rate,
        'Inflation_rate': inflation_rate,
        'GDP': gdp,
        'Application_mode': application_mode,
        'Application_order': application_order,
        'Course': course,
        'Mothers_qualification': mothers_qualification,
        'Fathers_qualification': fathers_qualification,
        'Mothers_occupation': mothers_occupation,
        'Fathers_occupation': fathers_occupation,
        'Displaced': displaced,
        'Gender': gender
    }

    submit = st.form_submit_button("Prediksi Status")

if submit:
    # Buat DataFrame input dengan urutan kolom yang benar
    input_df = pd.DataFrame([input_data], columns=feature_columns)

    # Preprocess dan predict
    X_processed = preprocessor.transform(input_df)
    prediction = model.predict(X_processed)[0]
    probas = model.predict_proba(X_processed)[0]

    st.success(f"**Prediksi Status: {label_map[prediction]}**")
    # Assuming probas are ordered for 0 and 1
    st.info(f"Probabilitas: Dropout={probas[0]:.2%}, Enrolled/Graduate={probas[1]:.2%}")

    # Feature importance jika tersedia
    # The model stored is GridSearchCV, so we access the best estimator.
    if hasattr(model.best_estimator_.named_steps['classifier'], 'feature_importances_'):
        st.subheader("Top 10 Feature Importance")
        importances = model.best_estimator_.named_steps['classifier'].feature_importances_
        # The feature names after preprocessing need to be derived for importance mapping
        # This requires reconstructing the feature names from the preprocessor

        num_features_out = numerical_cols
        cat_ohe_features_out = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)
        processed_feature_names = list(num_features_out) + list(cat_ohe_features_out)

        feat_imp = pd.DataFrame({'feature': processed_feature_names, 'importance': importances}).sort_values('importance', ascending=False)[:10]
        st.bar_chart(feat_imp.set_index('feature'))

# Footer
st.markdown("---")
st.caption("Proyek Akhir Dicoding: Prediksi Dropout Siswa Edutech [Juniyara Parisya Setiawan]")