# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uz40iNK4filGkvSLwXzUsDUycX68s9Ux

# Proyek Akhir: Menyelesaikan Permasalahan Perusahaan Edutech

- Nama: Juniyara Parisya Setiawan
- Email: parissajuniara@gmail.com
- Id Dicoding: juniyaraparisya

## Persiapan

### Menyiapkan library yang dibutuhkan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
from xgboost import XGBClassifier


import joblib

"""### Menyiapkan data yang akan diguankan"""

df = pd.read_csv('https://raw.githubusercontent.com/JunTheCoder62/Final-Project-Menyelesaikan-Permasalahan-Institusi-Pendidikan/refs/heads/main/Data/data.csv', delimiter=';')

df.head(5)

"""## Data Understanding"""

df.info()

df.isnull().sum()

"""tidak terdapat data yang memiliki missing value"""

df.duplicated().sum()

"""tidak terdapat data yang duplikat"""

df.nunique().sort_values(ascending = True)

"""Karena data sudah clean dan tidak memiliki missing value, data langsung digunakan."""

df['Status'].nunique()

np.sort(df['Status'].unique())

df['Status'].value_counts()

"""### Encoder data dari Object/Categorical menjadi numerical

Dikarenakan permasalahan pada Jaya Jaya Institusi adalah siswa yang tidak menyelesaikan pendidikan, dan data yang adalah merupakan tipe data Object/Categorical sehingga data harus diubah menjadi Numerical.
"""

Encoder = LabelEncoder()
df['Status'] = Encoder.fit_transform(df['Status'])
df.head()

# df_encoded = pd.get_dummies(df[['Status']], drop_first=True).astype(int)
# df_concat = pd.concat([df, df_encoded], axis=1)
# df_concat.head()

# label_encoder = LabelEncoder()
# df['Status_encoded'] = label_encoder.fit_transform(df['Status'])

# correlation_with_status = df.corr(numeric_only=True)['Status_encoded'].abs().sort_values(ascending=False)

# print("Correlation with 'Status' (absolute values, sorted descending):")
# print(correlation_with_status)

corr = df.select_dtypes(include=np.number).corr()
plt.figure(figsize=(20, 16))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt = ".2f", linewidths=0.5, annot_kws={"size": 8})
plt.title('Correlation Matrix', fontsize=16)
plt.show()

numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
correlation_matrix = df[numerical_features].corr().abs()
correlation_status = correlation_matrix['Status'].sort_values(ascending=False)
correlation_status

"""Didapat Matrix Korelasi untuk Status, dimana `Curricular_units_2nd_sem_approved` memiliki korelasi yang terbaik antara feature lainnya"""

df['Status'].value_counts()

"""count Status  
- Graduate 2209
- Dropout 1421
- Enrolled 794

## Data Preparation / Preprocessing
"""

median_status = df['Status'].median()
df['Status'].replace(2, median_status, inplace=True)

df['Status'] = df['Status'].astype(int)

print(df['Status'].value_counts())

x = df.drop(columns=['Status'])
y = df['Status']

x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    test_size=0.2,
                                                    random_state=42,
                                                    stratify=y)

x_train.shape, x_test.shape, y_train.shape, y_test.shape

print([len(x_train), len(y_train)])
print([len(x_test), len(y_test)])

y_train.value_counts(normalize=True)

y_test.value_counts(normalize=True)

"""## Modeling"""

# Normalisasi Data
scaler = StandardScaler()
df['Status'] = scaler.fit_transform(df[['Status']])
print(df)

# Random Forest
modem_rm = DecisionTreeClassifier()
modem_rm.fit(x_train, y_train)
predic_rf = modem_rm.predict(x_test)

print("akurasi:", accuracy_score(y_test, predic_rf))
print(classification_report(y_test, predic_rf))

numerical_cols = ['Previous_qualification_grade', 'Admission_grade', 'Age_at_enrollment',
                  'Curricular_units_1st_sem_credited', 'Curricular_units_1st_sem_evaluations',
                  'Curricular_units_1st_sem_grade', 'Curricular_units_1st_sem_without_evaluations',
                  'Curricular_units_2nd_sem_without_evaluations', 'Unemployment_rate',
                  'Inflation_rate', 'GDP']

categorical_cols = ['Application_mode', 'Application_order', 'Course', 'Mothers_qualification',
                    'Fathers_qualification', 'Mothers_occupation', 'Fathers_occupation',
                    'Displaced', 'Gender']

numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ]
)

X_train_processed = preprocessor.fit_transform(x_train)
X_test_processed = preprocessor.transform(x_test)

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_processed, y_train)

xgb_model = Pipeline(steps=[
    ('classifier', XGBClassifier())
])

param_space_xgb = {
    'classifier__n_estimators': [10, 20 ,50, 100],
    'classifier__max_depth': [3, 5, 7, 10],
    'classifier__gamma': [0.01, 0.1, 0.2, 0.3]
}

model_xgb = GridSearchCV(xgb_model, param_grid=param_space_xgb, cv=5)

model_xgb.fit(X_train_resampled, y_train_resampled)

print("Best Parameters:", model_xgb.best_params_)
print("Training Accuracy:", model_xgb.score(X_train_resampled, y_train_resampled))
print("Model Best Score (XGBoost):", model_xgb.best_score_)
print("Test Accuracy:", model_xgb.score(X_test_processed, y_test))

"""## Evaluation"""

y_pred_xgb = model_xgb.predict(X_test_processed)

print("\nConfusion Matrix XGBoost:")
print(confusion_matrix(y_test, y_pred_xgb))

print("\nClassification Report XGBoost:")
print(classification_report(y_test, y_pred_xgb))

joblib.dump(preprocessor, 'preprocessor_model.pkl')
joblib.dump(model_xgb, 'xgboost_model.pkl')